// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriber_publisher.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "subscriber_publisher.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace maxwell {
namespace protocol {

namespace {

const ::google::protobuf::EnumDescriptor* sub_type_t_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* pub_type_t_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_subscriber_5fpublisher_2eproto() {
  protobuf_AddDesc_subscriber_5fpublisher_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "subscriber_publisher.proto");
  GOOGLE_CHECK(file != NULL);
  sub_type_t_descriptor_ = file->enum_type(0);
  pub_type_t_descriptor_ = file->enum_type(1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_subscriber_5fpublisher_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_subscriber_5fpublisher_2eproto() {
}

void protobuf_AddDesc_subscriber_5fpublisher_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::maxwell::protocol::protobuf_AddDesc_subscriber_5fpublisher_5fstructs_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\032subscriber_publisher.proto\022\020maxwell.pr"
    "otocol\032\"subscriber_publisher_structs.pro"
    "to*K\n\nsub_type_t\022\r\n\tSUBSCRIBE\020\001\022\017\n\013UNSUB"
    "SCRIBE\020\002\022\024\n\020CLIENT_HEARTBEAT\020\003\022\007\n\003ACK\020\004*"
    "5\n\npub_type_t\022\024\n\020SERVER_HEARTBEAT\020\001\022\007\n\003M"
    "SG\020\002\022\010\n\004MSGS\020\003", 214);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "subscriber_publisher.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_subscriber_5fpublisher_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_subscriber_5fpublisher_2eproto {
  StaticDescriptorInitializer_subscriber_5fpublisher_2eproto() {
    protobuf_AddDesc_subscriber_5fpublisher_2eproto();
  }
} static_descriptor_initializer_subscriber_5fpublisher_2eproto_;
const ::google::protobuf::EnumDescriptor* sub_type_t_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return sub_type_t_descriptor_;
}
bool sub_type_t_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* pub_type_t_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return pub_type_t_descriptor_;
}
bool pub_type_t_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace maxwell

// @@protoc_insertion_point(global_scope)
