platform :ios, '8.0'
pod 'AFNetworking', '~>2.6.1'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJExtension', '~> 2.5.16'
pod 'UICKeyChainStore', '~> 2.1.0'
pod 'CocoaAsyncSocket', '~> 7.3.5'
pod 'FastCoding', '~> 3.2.1'
pod 'pop', '~> 1.0'
pod 'FLAnimatedImage', '~> 1.0'
